# Generated by Django 4.2.5 on 2023-10-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(verbose_name='километраж')),
                ('year', models.CharField(max_length=4, verbose_name='год')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.car', verbose_name='автомобиль')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.moto', verbose_name='мотоцикл')),
            ],
            options={
                'verbose_name': 'пробег',
                'verbose_name_plural': 'пробег',
            },
        ),
    ]
